In [10]:
import pandas as pd

In [19]:
import pandas as pd
testa = pd.read_csv('a.csv')
testb = pd.read_csv('b.csv')
print(a['school'][4])

University of California â€‹Irvine

In [20]:
a['school'][4]

'University of California \u200bIrvine'

In [15]:
testa.shape, testb.shape

((24, 14), (9, 5))

In [21]:
def clean(name):
    name = name.replace('\u200b','').rstrip()
    return name

testa['school'] = testa['school'].map(clean)
print(testa['school'][2])

df = pd.merge(testa, testb, on='school')

df

University of Southern California

,Unnamed: 0_x,school,test_optional,class_years,policy_details,number_of_applicants_int,acceptance_rate_float,sat_total_middle_range,act_total_middle_range,policy_check,sat_25th_percentile,sat_75th_percentile,act_25th_percentile,act_75th_percentile,Unnamed: 0_y,high_school_gpa_middle_range,gpa_25th_percentile,gpa_75th_percentile
0,24,University of California Los Angeles,Yes,2021 2022 2023 2024,The UC system has adopted a two-year test opti...,111322,0.123,1290-1510,27-34,Yes,1290.0,1510.0,27.0,34.0,3,4.19-4.32,4.19,4.32
1,33,University of California Berkeley,Yes (TB),2021 2022 2023 2024,Cal has adopted a four-year test blind policy ...,89621,0.148,1300-1530,28-34,Yes,1300.0,1530.0,28.0,34.0,0,4.12-4.30,4.12,4.30
2,60,University of California Irvine,Yes (TB),2021 2022 2023 2024,UCI has adopted a four-year test blind policy ...,95568,0.265,1180-1440,--,Yes,1180.0,1440.0,NaN,NaN,2,3.96-4.26,3.96,4.26
3,69,University of California Santa Barbara,Yes,2021 2022 2023 2024,The UC system has adopted a two-year test opti...,93457,0.296,1260-1460,25-33,Yes,1260.0,1460.0,25.0,33.0,7,4.10-4.29,4.10,4.29
4,72,University of California San Diego,Yes,2021 2022 2023 2024,The UC system has adopted a two-year test opti...,97901,0.302,1250-1470,26-33,Yes,1250.0,1470.0,26.0,33.0,6,4.07-4.29,4.07,4.29
5,108,University of California Davis,Yes,2021 2022 2023 2024,The UC system has adopted a two-year test opti...,76647,0.412,1150-1410,25-31,Yes,1150.0,1410.0,25.0,31.0,1,3.95-4.25,3.95,4.25
6,143,University of California Santa Cruz,Yes (TB),2021 2022 2023 2024,UCSC has adopted a four-year test blind policy...,55906,0.515,1200-1360,24-30,Yes,1200.0,1360.0,24.0,30.0,8,3.81-4.20,3.81,4.20
7,160,University of California Riverside,Yes,2021 2022 2023 2024,The UC system has adopted a two-year test opti...,49788,0.567,1130-1340,24-30,Yes,1130.0,1340.0,24.0,30.0,5,3.7-4.13,3.70,4.13
8,269,University of California Merced,Yes,2021 2022 2023 2024,The UC system has adopted a two-year test opti...,25368,0.720,980-1180,17-22,Yes,980.0,1180.0,17.0,22.0,4,3.39-4.00,3.39,4.00

In [17]:
df.shape

(9, 18)